# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: 0 4 * * *
  branches:
    include:
    - master
  always: true
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: eshop-identity-api
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.x
    inputs:
      version: 6.x
  - task: DockerInstaller@0
    displayName: Install Docker 20.10.9
    inputs:
      dockerVersion: 20.10.9
  - task: Docker@2
    displayName: login
    inputs:
      containerRegistry: 3ec4decc-f585-4b57-ad20-058527a0fd18
      command: login
  - task: Bash@3
    displayName: Install Buildx
    inputs:
      targetType: inline
      script: >-
        # Write your commands here
        echo 'Install Buildx'

        docker buildx create --name multi-platform-builder --driver docker-container

        docker buildx use multi-platform-builder

        docker run --privileged --rm tonistiigi/binfmt --install all

  - task: Bash@3
    displayName: Build & Push Image
    inputs:
      targetType: inline
      script: docker buildx build --platform linux/arm64,linux/amd64 -t registry.cn-hangzhou.aliyuncs.com/zhangjj/demo:eshop-identity-api --push -f ./src/Services/Basket/Basket.API/Dockerfile .
      workingDirectory: MicroserviceDemo
  - task: Docker@2
    displayName: logout
    inputs:
      containerRegistry: 3ec4decc-f585-4b57-ad20-058527a0fd18
      command: logout
  - task: Bash@3
    displayName: Notify
    inputs:
      targetType: inline
      script: >-
        # Write your commands here
        echo '--Start--'

        #echo `curl --location --request GET 'https://seoul-arm.zhangjin.tk:31515/hook?access_key=4RyWV1DQl0TlogKb2HNei2njgcEQBl3WhjR2A6gTfVnEcJrJ&param=auth-server,abp-authserver-host'`

        echo '---End---'

